Add an user manual page
tweag/nickel-lang.org pull request #44
Opened 2022-02-28 16:56 UTC by yannham

WIP. Install required packages to get markdown support for gatsby, set nickel-manual as the source for manual pages in markdown, add a sidebar-tocs component for the table of content, and add pages corresponding to each markdown file in the route `user-manual/xxx`.

TODO:

 - [x] install required packages for markdown support in gatsby
 - [x] add a page for each markdown file as `/user-manual/xxx`
 - [x] enable prisms.js support with the custom Nickel syntax highlighter
 - [x] add a sidebar menu
 - [ ] automatize the download of the manual from the nickel flake into `nickel-manual`
 - [ ] add the required metadata to the manual sections in the `nickel` repo (a `slug` field)
 - [ ] add missing introduction and quickstart sections
 - [ ] add redirections from "foo.md" to "foo" to make manual's intralinks work
 - [ ] make the menu on the left sticky (maybe later)
 - [ ] have sub-menus corresponding to subsections (maybe later)

2022-03-10 15:34 UTC, ErinvanderVeen requested changes
- There is a missing ) in "Current state and roadmap", notably about the custom merge functions
- The wrong link to "getting started" at https://622a0f4a313c8144d3bdc420--nickel-lang.netlify.app/user-manual/introduction/#getting-started could be replaced with a relative link to avoid the netlify issue.
- The table headers (for example the Operators, Associativity, Remark table in the syntax chapter) are very close to one another.
- The syntax highlighting is sometimes broken, for instance only the "in" in "builtin" and "min" is highlighted. Could we enforce that "in" starts and ends with a word bound: "<in>"?
- "The reader can find more information about merging in the relevant documentation." It would be nice if there was a link to that documentation somewhere in that sentence.
- Do we want the specifications as part of the user manual? For me, it disrupts the flow of reading.
- There are many places where we have a monospace text, for example in examples, but sometimes also error messages. I think these texts should be more easily distinguishable from the surrounding (non monospace) text. Either by displaying them with a dark background, like we do for some of the code examples, or at least surrounded by a border.
- There is a (leftover footmark) in the correctness chapter: "This statement is to be nuanced. Using the Nickel LSP server in your"
- The "User-defined contracts" should have some text below it. Perhaps: "There are two ways to construct contracts: by hand, and by using the `from_predicate` function"

2022-03-10 15:34 UTC, ErinvanderVeen commented on src/styles/custom.scss
>  }
Missing newline

2022-03-10 16:14 UTC, yannham commented
Thanks for reviewing! I'll look into it.

As a preliminary answers:

- The text of the manual is directly taken from the Nickel repo, so fixing text is (surprisingly, maybe) out of scope of this PR. But that's till useful information to patch the nickel-repo directly.
- Syntax highlighting has to be updated, yeah, but I think I'll do that in a subsequent PR. It's not specific to the manual.
- I agree about table headers, but I use a generic Gatsby plugin to transform md files to HTML. I'll take a quick look if it is easily customizable, but I don't plan to spend too much time on tweaking the default.
- The wrong link to `Getting Started` can't be fixed: it comes from the manual inside the Nickel repo, which is distributed as standalone MD files that could be read from anywhere. Hence, we need an absolute link to make it work inside MD files. That's also fine IMHO because once this PR is merged, it becomes an non-issue.

2022-03-10 17:03 UTC, yannham commented on src/pages/getting-started.js
> +                <p>If you are planning to try Nickel a bit more extensively, you can build the binary to avoid having to go through Nix at each execution (works for Nix versions prior to 2.4.0 too):<
Good suggestion

2022-03-10 17:42 UTC, yannham commented on src/pages/user-manual/{MarkdownRemark.frontmatter__slug}.js
> +                </div>
That's strange, I don't experience the same, whatever I try.

2022-03-10 18:27 UTC, yannham commented
And now rebase on the grammar fix.

2022-03-11 09:03 UTC, ErinvanderVeen approved these changes

2022-03-11 09:08 UTC, merged